version: '3.6'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hw9
      MYSQL_USER: hw9
      MYSQL_PASSWORD: pass
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
